特征选择

In [1]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold

X = np.array([
       [1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.]
])
X.shape

(4, 13)

In [2]:
XX = VarianceThreshold(threshold=0.01).fit_transform(X)
XX

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.]])

In [3]:
XX.shape

(4, 12)

In [6]:
import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif
X = np.array([
    [1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.],
    [6., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.],
    [10., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.],
    [13., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.],
])
y = [1, 1, 0, 0]

sk = SelectKBest(f_classif)
sk.fit_transform(X, y)
sk.scores_


array([7.52941176, 1.        , 1.        , 0.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.        , 0.        , 0.        ])

In [7]:
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

X = np.array([
    [1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.],
    [6., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.],
    [10., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.],
    [13., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.],
])
y = [1, 1, 0, 0]

sk = SelectKBest(chi2)
sk.fit_transform(X, y)
sk.scores_


array([8.53333333, 1.        , 1.        , 0.        , 0.33333333,
       1.        , 1.        , 0.33333333, 1.        , 1.        ,
       0.        , 0.        , 0.        ])

In [8]:
import numpy as np
from sklearn.feature_selection import SelectKBest, mutual_info_classif

X = np.array([
    [1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1.],
    [6., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.],
    [10., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.],
    [13., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.],
])
y = [1, 1, 0, 0]

sk = SelectKBest(mutual_info_classif)
sk.fit_transform(X, y)
sk.scores_

array([0.08333333, 0.        , 0.        , 0.        , 0.08333333,
       0.        , 0.        , 0.08333333, 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [10]:
import numpy as np

X = np.array([
    [1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1.],
    [6., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1.],
    [10., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.],
    [13., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
])
corr = np.corrcoef(X, rowvar=False)
corr[-1,:]

array([-0.88888889,  0.57735027, -0.57735027,  0.        ,  0.57735027,
       -0.57735027, -0.57735027,  0.57735027, -0.57735027,  0.57735027,
        0.        ,  0.        ,  0.        ,  1.        ])